classDiagram

class PresentationLayer {
  <<Layer>>
  ServiceAPI
}

namespace BusinessLogicLayer {
  class HBnBFacade {
    <<facade>>
    +register_user()
    +create_place()
    +submit_review()
    +list_places()
  }
  class DomainModel {
    Models
    BusinessRules
  }
}

class PersistenceLayer {
  <<Layer>>
  Repositories
  Storage
}

PresentationLayer --> HBnBFacade : &nbsp Calls &nbsp
HBnBFacade --> DomainModel : &nbsp Orchestrates &nbsp
DomainModel --> PersistenceLayer : &nbsp Uses (repositories) &nbsp